---
title: "Electricity Production in Romania (2019-2022)"
output: html_document
date: '`r Sys.Date()`'
---

```{r echo=FALSE, warning=FALSE, message=FALSE, results='hide'}
#initial setup & files
library(RColorBrewer)
library(plyr)
library(reshape2)
library(tidyverse)

setwd("/Users/home/Downloads/5. Github Public Repos/Daily-Electricity-in-Romania--2019-2023--EDA")

romaniaElectricity <- read.csv("datasets/daily_electricity_data.csv")
romaniaElectricity <- romaniaElectricity %>%
  mutate(DateTime = as.Date(DateTime)) %>%
  filter(DateTime < "2023-01-01") #keeping the data exactly for 4 years (2019-2022)
```



```{r}
#Total Production by Year

productionByYear <- romaniaElectricity %>%
  mutate(Year = format(DateTime, "%Y")) %>%
  group_by(Year) %>%
  mutate(Consumption = sum(Consumption),
    Production = sum(Production),
    Nuclear = sum(Nuclear),
    Wind = sum(Wind),
    Hydroelectric = sum(Hydroelectric),
    "Oil and Gas" = sum(Oil.and.Gas),
    Coal = sum(Coal),
    Solar = sum(Solar),
    Biomass = sum(Biomass)) %>%
  mutate_if(is.numeric, function(x){x / 1000}) %>%
  select(-DateTime, -Consumption, -Oil.and.Gas) %>%
  summarise_all(mean)

productionByYear <- melt(productionByYear, 
                         id.vars = c("Year", "Production"),
                         variable.name = "Technology",
                         value.name = "Technology_Production") %>%
  arrange(Year)

ggplot(productionByYear, aes(x = Year, y = Technology_Production,
                             fill = fct_reorder(Technology, Technology_Production, 
                                                .desc = TRUE))) + 
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Year",
       y = "Production (GWh)",
       title = "Total Electricity Production by Year\nRomania (2019-2022)",
       subtitle = "source: data.world",
       fill = "Technology") +
  scale_fill_manual(values=c("#8DA0CB", "#E78AC3", "#B3B3B3", "#FFD92F",
                             "#A6D854", "#FC8D62", "#66C2A5")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 12, hjust=0.5),
        plot.subtitle = element_text(size = 8, hjust=0.5),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10))

#save the graph
ggsave("outputs/graph1.jpg", width = 1920, height = 1080, units = "px")
```


```{r}
#Production by Technology Type

productionByTechnology <- melt(romaniaElectricity,
                               id.vars = c("DateTime", "Consumption", "Production"),
                               variable.name = "Technology",
                               value.name = "Technology_Production") %>%
  mutate(Technology_Production = Technology_Production / 1000) %>% #transform to GWh
  arrange(DateTime) %>%
  group_by(Technology) %>%
  mutate(Median_Production = median(Technology_Production)) %>%
  ungroup()

#changing one of the levels
productionByTechnology$Technology <- revalue(productionByTechnology$Technology,
                                             c("Oil.and.Gas" = "Oil and Gas"))

#sorting the levels in factor
productionByTechnology$Technology <- fct_reorder(productionByTechnology$Technology, productionByTechnology$Median_Production)

ggplot(productionByTechnology, aes(x = Technology_Production, y = Technology, fill = Technology)) +
  geom_boxplot() +
  scale_x_continuous(limits = c(0,105), 
                     breaks = c(0,10,20,30,40,50,60,70,80,90,100), 
                     expand = c(0,0)) +
  labs(title = "Daily Electricity Production by Technology Type\n Romania (2019-2022)",
       subtitle = "source: data.world",
       x = "Production (GWh)",
       y = "") + 
  scale_fill_manual(values=c("#66C2A5", "#FC8D62", "#A6D854", "#FFD92F",
                             "#B3B3B3", "#E78AC3", "#8DA0CB")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 12, hjust=0.5),
        plot.subtitle = element_text(size = 8, hjust=0.5),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.title.x = element_text(size = 12, vjust = -0.5),
        legend.position = "none",
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())

#save the graph
ggsave("outputs/graph2.jpg", width = 1920, height = 1080, units = "px")
```

```{r}
#Wind Production by Month

windProductionByMonth <- romaniaElectricity %>%
  select(DateTime, Wind) %>%
  mutate(Month = format(DateTime, "%m")) %>%
  group_by(Month) %>%
  mutate(Wind_Month_Median = median(Wind) / 1000) %>% #GWh
  select(-DateTime, -Wind) %>%
  mutate(Month = factor(Month, 
                        levels = c("01", "02", "03", "04", "05", "06",
                                   "07", "08", "09", "10", "11", "12"),
                        labels = c("January", "February", "March",
                                   "April", "May", "June",
                                   "July", "August", "September",
                                   "October", "November", "December"))) %>%
  summarise_all(mean)

ggplot(windProductionByMonth, aes(x = Month, y = Wind_Month_Median)) +
  geom_bar(stat = "identity", width = 0.7, fill = "#A6D854", color = "#000000") +
  scale_y_continuous(limits = c(0,26), breaks = c(0,5,10,15,20,25)) +
  labs(title = "Median Wind Electricity Production by Month\nRomania (2019-2022)",
       subtitle = "source: data.world",
       x = "",
       y = "Production (GWh)") +
  theme_minimal() +
  theme(plot.title = element_text(size = 12, hjust=0.5),
        plot.subtitle = element_text(size = 8, hjust=0.5),
        axis.text.x = element_text(size = 10, angle = 45, vjust = 1.2, hjust = 1.1),
        axis.text.y = element_text(size = 10),
        axis.title.y = element_text(size = 12, vjust = 0.5),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank()) +
  geom_text(aes(label = round(Wind_Month_Median)), vjust = -0.4)
  

#save the graph
ggsave("outputs/graph3.jpg", width = 1920, height = 1080, units = "px")
```
